# Generated by Django 2.1.7 on 2019-03-17 06:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodqty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('cuisine', models.CharField(max_length=100)),
                ('course', models.CharField(choices=[('s', 'Starter'), ('m', 'Main Course'), ('d', 'Desert')], max_length=1)),
                ('price', models.IntegerField()),
                ('availability_time', models.TimeField()),
                ('ordercount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodlist', models.CharField(max_length=500, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('foodqty', models.CharField(max_length=500, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('amount', models.IntegerField(default=0)),
                ('ordertime', models.TimeField()),
                ('orderdate', models.DateField(auto_now_add=True)),
                ('deliverystatus', models.CharField(choices=[('p', 'Pending'), ('d', 'Delivered')], default='p', max_length=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foody.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('res_type', models.CharField(choices=[('B', 'Bar'), ('R', 'Restaurant'), ('C', 'Cafe')], default='R', max_length=1)),
                ('cuisine', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('imgurl', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foody.Restaurant'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='resid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foody.Restaurant'),
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foody.Customer'),
        ),
        migrations.AddField(
            model_name='cart',
            name='fooditems',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foody.FoodItem'),
        ),
    ]
