# Generated by Django 2.1.7 on 2019-03-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foody', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cuisine',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='imgurl',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
